name: Custom Feature Report
description: File a feature report
title: "[Feature]: "
labels: ["feature", "triage"]
projects: ["octo-org/1", "octo-org/44"]
assignees:
  - AyeNyeinSanISRubi
body:
  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: What is your name?
      placeholder: ex. Aye Nyein San
    validations:
      required: false
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report!
  - type: dropdown
    id: typeOfRequest 
    attributes:
      label: Type of request?
      description: Select the type of your request
      options:
        - New Feature
        - Existing Feature
      default: 0
    validations:
      required: true
  - type: dropdown
    id: browsers
    attributes:
      label: What is the OS that you want to suggest?
      multiple: true
      options:
        - ChromeOS
        - LinuxOS
        - WindowsOS
        - MacOS (OSX)
  - type: textarea
    id: FeatureDetails
    attributes:
      label: What are the details of your suggestion?
      description: Explain what do you want
      placeholder: Feature Details!!!

